// <auto-generated />
using System;
using Leo.Services.Muses.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leo.Services.Muses.Migrations
{
    [DbContext(typeof(MusesDbContext))]
    partial class MusesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497");

            modelBuilder.Entity("Leo.Services.Muses.Entities.Criticism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Critic");

                    b.Property<string>("Opinion")
                        .IsRequired();

                    b.Property<int>("SingerId");

                    b.HasKey("Id");

                    b.HasIndex("SingerId");

                    b.ToTable("Criticisms");
                });

            modelBuilder.Entity("Leo.Services.Muses.Entities.Singer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("BriefBiography");

                    b.Property<DateTime>("DeathDate");

                    b.Property<string>("Name");

                    b.Property<string>("OriginName");

                    b.HasKey("Id");

                    b.ToTable("Singers");
                });

            modelBuilder.Entity("Leo.Services.Muses.Entities.SingerSong", b =>
                {
                    b.Property<int>("SingerId");

                    b.Property<int>("SongId");

                    b.HasKey("SingerId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("SingerSong");
                });

            modelBuilder.Entity("Leo.Services.Muses.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Composer");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TranslatedName");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Leo.Services.Muses.Entities.Criticism", b =>
                {
                    b.HasOne("Leo.Services.Muses.Entities.Singer", "Singer")
                        .WithMany("Criticisms")
                        .HasForeignKey("SingerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Leo.Services.Muses.Entities.SingerSong", b =>
                {
                    b.HasOne("Leo.Services.Muses.Entities.Singer", "Singer")
                        .WithMany("SingerSongs")
                        .HasForeignKey("SingerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Leo.Services.Muses.Entities.Song", "Song")
                        .WithMany("SingerSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
